server:
  port: 8080
  servlet:
    context-path: /sso

spring:
  freemarker:
    request-context-attribute: request
    suffix: .ftl  #后缀名
    content-type: text/html
    enabled: true
    cache: false #缓存配置
    template-loader-path: classpath:/templates/ #模板加载路径 按需配置
    charset: UTF-8 #编码格式
    settings:
      number_format: '0.##'   #数字格式化，无小数点
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB