social:
  wx:
    appid:  1111
    appSecret: 1111

spring:
  datasource:
    username: root
    password: 123456
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/test
  freemarker:
    request-context-attribute: request
    suffix: .html
    content-type: text/html
    enabled: true
    cache: false
    template-loader-path: classpath:/templates/
    charset: UTF-8
    settings:
      number_format: '0.##'
  security:
    user:
      name: user
      password: admin
      roles: user, admin

