
social:
  wx:
    app-id:  101841584
    app-secret: 1111
  qq:
    app-id:  101838095
    app-secret: af20f3f090b9b172239a1ed22abc73f5


spring:
  datasource:
    username: root
    password: 123456
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/test
  freemarker:
    request-context-attribute: request
    suffix: .html
    content-type: text/html
    enabled: true
    cache: false
    template-loader-path: classpath:/templates/
    charset: UTF-8
    settings:
      number_format: '0.##'
  security:
    user:
      name: user
      password: admin
      roles: user, admin
server:
  port: 443
  ssl:
    key-store: classpath:server.keystore
    key-alias: tomcat
    enabled: true
    key-store-password: wangle
    key-store-type: JKS
